add_library(MokshaMiddle
    hir/HIRExpr.cpp
    hir/HIRFunction.cpp
    hir/HIRGen.cpp
    hir/HIRModule.cpp
    hir/HIRStmt.cpp
    hir/HIRType.cpp
    hir/LowerASTToHIR.cpp
    mir/MIRBlock.cpp
    mir/MIRBuilder.cpp
    mir/MIRFunction.cpp
    mir/MIRInst.cpp
    mir/MIRVerifier.cpp
    analysis/MIRDominance.cpp
    passes/LowerHIRToMIR.cpp
    passes/VerifyNoMacros.cpp
    ownership/ARCAnalyzer.cpp
    ownership/ARCInserter.cpp
    ownership/BorrowChecker.cpp
)

target_link_libraries(MokshaMiddle
    PUBLIC
    mokshaSettings
    MokshaSupport
    LLVMCore
    mokshaFrontend
)
