#include "../../include/moksha_rt.h"
#include "../abi/sys_caps.h"
#include "../abi/sys_event.h"

// Bring in Windows API for the console fix
#ifdef _WIN32
#include <windows.h>
#endif

// Generated by MLIRToLLVM pass
extern void __moksha_module_init(void);
extern void __moksha_module_destroy(void);

// FIX: Declare the Moksha entry point with CLI arguments
extern void __moksha_main(int argc, char **argv);

// Provided by src/async/scheduler.c
extern void moksha_scheduler_init(void);
extern void moksha_scheduler_run(void);
extern bool moksha_scheduler_is_active(void);

// The REAL entry point that the OS and Linker will call
int main(int argc, char **argv) {
  // Force Windows Console to render UTF-8
#ifdef _WIN32
  SetConsoleOutputCP(CP_UTF8);
#endif

  const sys_caps_t *caps = sys_get_caps();

  // 1. Initialize Async Event Loop if the platform supports it
  if (caps->has_async_io) {
    sys_event_init();
    moksha_scheduler_init();
  }

  // 2. Execute global LLVM constructors (Initializes your strings!)
  __moksha_module_init();

  // FIX: 3. Run the user's program and pass the OS arguments forward
  __moksha_main(argc, argv);

  // Keep pumping the scheduler until all async tasks are complete.
  if (caps->has_async_io) {
    while (moksha_scheduler_is_active()) {
      moksha_scheduler_run();
    }
  }

  // 4. Cleanup
  __moksha_module_destroy();

  return 0;
}
